#!/usr/bin/env bash
###############################################################################
# sync-nginx-map.sh — Regenerate customers.map from SQLite
#
# Queries the ClawDaddy SQLite database for all provisioned customers,
# generates /etc/nginx/clawdaddy/customers.map, and reloads nginx.
#
# Usage: sudo bash sync-nginx-map.sh
#
# Can be run:
#   - As part of deploy process
#   - As a cron job (every 5 min) for self-healing
#   - Manually via: manage.sh sync-nginx
###############################################################################
set -euo pipefail

DB_PATH="${DB_PATH:-/home/ubuntu/clawdaddy/data/clawdaddy.db}"
MAP_FILE="/etc/nginx/clawdaddy/customers.map"
MAP_DIR="$(dirname "${MAP_FILE}")"

# Ensure map directory exists
mkdir -p "${MAP_DIR}"

# Check if sqlite3 is available
if ! command -v sqlite3 &>/dev/null; then
    echo "ERROR: sqlite3 not found. Install with: sudo apt install sqlite3"
    exit 1
fi

# Check if DB exists
if [[ ! -f "${DB_PATH}" ]]; then
    echo "ERROR: Database not found at ${DB_PATH}"
    exit 1
fi

# Query: get username and server_ip for all provisioned customers
ENTRIES=$(sqlite3 "${DB_PATH}" \
  "SELECT username, server_ip FROM customers WHERE provision_status = 'ready' AND server_ip IS NOT NULL AND username IS NOT NULL;" \
  2>/dev/null || true)

if [[ -z "${ENTRIES}" ]]; then
    echo "No provisioned customers found. Writing empty map file."
    {
        echo "# Auto-generated by sync-nginx-map.sh — $(date -Iseconds)"
        echo "# No provisioned customers"
    } > "${MAP_FILE}"
else
    # Write map file atomically (write to .tmp then move)
    {
        echo "# Auto-generated by sync-nginx-map.sh — $(date -Iseconds)"
        echo "# DO NOT EDIT MANUALLY — changes will be overwritten"
        echo ""
        echo "${ENTRIES}" | while IFS='|' read -r username ip; do
            if [[ -n "${username}" && -n "${ip}" ]]; then
                echo "${username} ${ip}:443;"
            fi
        done
    } > "${MAP_FILE}.tmp"

    mv "${MAP_FILE}.tmp" "${MAP_FILE}"
    ENTRY_COUNT=$(echo "${ENTRIES}" | wc -l | tr -d ' ')
    echo "Wrote ${ENTRY_COUNT} entries to ${MAP_FILE}"
fi

# Reload nginx
if nginx -t 2>/dev/null; then
    nginx -s reload
    echo "nginx reloaded successfully"
else
    echo "WARNING: nginx config test failed — NOT reloading"
    exit 1
fi
